# Generated by Django 4.0.4 on 2022-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_user_comment_poster_comment_on_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
