# Generated by Django 4.0.4 on 2022-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_listing_owner_bid_open_bid_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default='True'),
        ),
    ]
