# Generated by Django 4.0.4 on 2022-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default='False'),
        ),
    ]
